language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - node --version
script:
  - npm run test
# after_success:
#   - npm run coverage
