language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
os:
  # - windows -> early access at the moment, we shouldn't use it
  - linux
  - osx
# prepare for v12
# matrix:
#   allow_failures:
#   - node: 12
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
# after_success:
#   - npm run coverage
